/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.32-MariaDB-log : Database - world
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
USE `world`;

/*Data for the table `command` */

insert  into `command`(`name`,`permission_mask`,`help`) values ('account',1,'Syntax: .account\r\nShows account type.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account create',2048,'Syntax: .account create $account $password\r\nCreate account and set password to it.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account delete',4096,'Syntax: .account delete $account\r\nDelete account with all characters.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account gann',1,'Syntax: .account gann\r\nEnables/Disables guild accounce display for account');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account log',2048,'Syntax: .account log $account\r\nEnables special log on given account.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account onlinelist',4096,'Syntax: .account onlinelist\r\nShow list of online accounts.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account set addon',2048,'Syntax: .account set addon [$account] #addon\r\nSet user (posible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk, 3 - cata.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account set password',4096,'Syntax: .account set password $account $password $password\r\nSet password for account.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account set permissions',2048,'Syntax: .account set gmlevel [$account] #level\r\nSet the security level for targeted player (can\'t be used at self) or for account $name to a level of #level. #level may range from 0 to 3.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('account whisp',2048,'Syntax: .account whisp $account\r\nEnables account whisp log');
insert  into `command`(`name`,`permission_mask`,`help`) values ('additem',2048,'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added..');
insert  into `command`(`name`,`permission_mask`,`help`) values ('additemset',2048,'Syntax: .additemset #itemsetid\r\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('allowmove',8192,'Syntax: .allowmove\r\nAllow/Disallow movement on server.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('announce',512,'Syntax: .announce #text\r\nShows system message with #text');
insert  into `command`(`name`,`permission_mask`,`help`) values ('aura',512,'Syntax: .aura #spellid\r\nAdd the aura from spell #spellid to the selected Unit.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ban account',512,'Syntax: .ban account $login $time $reason\r\nBans given account for given time with given reason.\r\neg: .ban account test 1d plum plum\r\nFor perm type -1 in $time.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ban character',512,'Syntax: .ban character $nick $time $reason\r\nBans given character account for given time with given reason.\r\neg: .ban character Plum 1d plum plum plum\r\nFor perm type -1 in $time.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ban email',2048,'Syntax: .ban email $email $reason\r\nBans permanently given email with given reason.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ban ip',512,'Syntax: .ban ip $ip $time $reason\r\nBans given ip (with accounts on this ip) for given time with given reason.\r\neg: .ban IP 3213.321321.2 3d plum plum\r\nFor perm type -1 in $time.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('baninfo account',512,'Syntax: .baninfo account $account\r\nWatch full information about a specific account ban.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('baninfo character',512,'Syntax: .baninfo character $nick\r\nWatch full information about a specific character ban.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('baninfo email',2048,'Syntax: .baninfo email $email\r\nWatch full information about a specific email ban.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('baninfo ip',512,'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ip ban.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('bank',256,'Syntax: .bank\r\nShow your bank inventory.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('banlist account',256,'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('banlist character',256,'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('banlist email',2048,'Syntax: .banlist email $email\r\nSearches the banlist for a email pattern.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('banlist ip',512,'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('bindfollow',2,'Syntax: .bindfollow\r\nBinds character to follow selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('bindsight',2,'Syntax: .bindsight\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cast',256,'Syntax: .cast #spellid [triggered]\r\nCast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cast back',256,'Syntax: .cast back #spellid [triggered]\r\nSelected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cast dist',2048,'Syntax: .cast dist #spellid [#dist [triggered]]\r\nYou will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cast null',2,'Syntax: .cast null #spellid\r\nYou (or selected unit) will cast spell #spellid with NULL target.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cast self',256,'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cast target',2048,'Syntax: .cast target #spellid [triggered]\r\nSelected target will cast #spellid to his current victim. If \'trigered\' or part provided then spell casted with triggered flag.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cd',2048,'Syntax: .cd [#spell_id]\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('channel kick',2048,'Syntax: .channel kick #channelname #playername\r\nKicks player with #playername from channel #channelname.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('channel list',2048,'Syntax: .channel list\r\nPrints list with custom channel names.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('channel masskick',2048,'Syntax: .channel masskick #channelname\r\nKicks all players from channel #channelname.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('channel pass',2048,'Syntax: .channel pass #channelname #pass\r\nSets password #pass on channel #channelname.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('chardelete',2048,'Syntax: .chardelete $charactername\r\nDelete character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('combatstop',256,'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cometome',2,'Syntax: .cometome $flags\r\nForce selected creature to move to command user actual position using given movement flags.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('commands',1,'Syntax: .commands\r\nDisplay a list of available commands for your account level.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('cooldown',2048,'Syntax: .cooldown [#spell_id]\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('crash map',2048,'Syntax: .crash map\r\nSets map as broken to simulate map crash.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('crash server',4096,'Syntax: .crash server\r\nCrashes whole server ^^.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('damage',2048,'Syntax: .damage $damage_amount [$school [$spellid]]\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug anim',2,'Syntax: .debug anim #emoteid\r\nPlay emote #emoteid for your character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug arena',4096,'Syntax: .debug arena\r\nToggles arena 1v1 or normal mode.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug bg',4096,'Syntax: .debug bg\r\nToggles battleground 1v1 or normal mode.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug getinstdata',2,'Syntax: .debug getinstdata64 $id\r\nReturns instance data64 (mostly npc/game obj guids) with id $id from current instance. Data64 id depends on instance implementation.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug getitemstate',4096,'Syntax: .debug getitemstate unchanged/changed/new/removed/queue/check_all\r\nLists all items from selected player matching given item state.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug getvalue',2,'Syntax: .debug getvalue #field #isInt\r\nGet the field #field of the selected creature. If no creature is selected, get the content of your field.\r\nUse a #isInt of value 1 if the expected field content is an integer.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug lootrecipient',2,'Syntax: .debug lootrecipient\r\nReturns lootrecipient for selected creature.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug Mod32Value',2048,'Syntax: .debug Mod32Value #index #value\r\nModify 32 bit value with index #index by value #value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug play cinematic',2,'Syntax: .debug play cinematic #cinematicid\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug play sound',2,'Syntax: .debug play sound #soundid\r\nPlay sound with #soundid. Sound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug poolstats',2,'Syntax: .debug poolstats #entry #range\r\nReturns pool statistics for gameobjects with entry #entry in range #range.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send buyerror',256,'Syntax: .debug send buyerror #msg\r\nSend buyerror with error msg #msg (uint8) to player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send channelnotify',2048,'Syntax: .debug send channelnotify #type\r\nSend channel notify on channel test using notify type #type.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send chatmessage',2048,'Syntax: .debug send chatmessage #type\r\nSend chat message on channel test using notify type #type.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send equiperror',256,'Syntax: .debug send equiperror #msg\r\nSend equip error with error msg #msg (uint8) to player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send opcode',4096,'Syntax: .debug send opcode\r\nSends opcode with opcode informations stored in opcode.txt file.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send qinvalidmsg',4096,'Syntax: .debug send qinvalidmsg #msg\r\nSends quest invalid msg (uint32).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send qpartymsg',4096,'Syntax: .debug send qpartymsg #msg\r\nSends quest party msg (uint32).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send sellerror',4096,'Syntax: .debug send sellerror #msg\r\nSends sell error with msg #msg(uint8).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug send spellfail',4096,'Syntax: .debug send spellfail #failnum #failarg1 #failarg2\r\nSends spell fail error msg with gived data.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug setinstdata',256,'Syntax: .debug setinstdata #id #value\r\nSets current instance data with id #id to value #value. Data id depends on instance implementation.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug setinstdata64',256,'Syntax: .debug setinstdata64 #id #value\r\nSets current instance data64 (mostly creature/GO guids) with id #id to value #value. Data64 id depends on instance implementation.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug setitemflag',2048,'Syntax: .debug setitemflag #guid #flag\r\nSets flags #flag to item with guid #guid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug setvalue',2048,'Syntax: .debug setvalue #field #value #isInt\r\nSet the field #field of the selected creature with value #value. If no creature is selected, set the content of your field. Use a #isInt of value 1 if #value is an integer.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug showcombatstats',1,'Syntax: .debug showcombatstats on/off\r\nEnable or disable extended combat stat show on chat');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug threatlist',1,'Syntax: .debug threatlist\r\nPrints out the current threatlist of the targetted creature.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug update',4096,'Syntax: .debug update #field #value\r\nUpdate the field #field of the selected character or creature with value #value.\r\nIf no #value is provided, display the content of field #field.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('debug uws',4096,'Syntax: .debug uws #world #state\r\nUpdate #world state with #state value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('demorph',2,'Syntax: .demorph\r\nDemorph the selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('die',2048,'Syntax: .die\r\nKill the selected player. If no player is selected, it will kill you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('dismount',2,'Syntax: .dismount\r\nDismount you, if you are mounted.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('distance',2,'Syntax: .distance\r\nDisplay the distance from your character to the selected creature.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('event',2,'Syntax: .event #event_id\r\nShow details about event with #event_id.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('event activelist',2,'Syntax: .event activelist\r\nShow list of currently active events.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('event start',2048,'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('event stop',2048,'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('explorecheat',4096,'Syntax: .explorecheat #flag\r\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('flusharenapoints',8192,'Syntax: .flusharenapoints\r\nUse it to distribute arena points based on arena team ratings, and start a new week.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('freeze',512,'Syntax: .freeze [#player]\r\n\"Freezes\" #player and disables his chat. When using this without #name it will freeze your target.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm',2,'Syntax: .gm on/off\r\nEnable or Disable in game GM MODE.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm announce',4096,'Syntax: .gm announce $announcement\r\nSend an announcement to online Gamemasters.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm chat',512,'Syntax: .gm chat on/off\r\nEnable or disable chat GM MODE (show gm badge in messages).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm fly',2,'Syntax: .gm fly on/off\r\nEnable/disable gm fly mode.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm list',2048,'Syntax: .gm list\r\nDisplay a list of all Game Masters accounts and security levels.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm nameannounce',2048,'Syntax: .gm nameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm notify',2048,'Syntax: .gm notify $notification\r\nDisplays a notification on the screen of all online GM\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gm visible',512,'Syntax: .gm visible on/off\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go creature',2,'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go graveyard',2,'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go grid',2,'Syntax: .go grid #gridX #gridY [#mapId]\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go object',2,'Syntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go ticket',512,'Syntax: .go ticket #ticketid\r\nTeleports the user to the location where $ticketid was created.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go trigger',2,'Syntax: .go trigger #trigger_id\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go xy',2,'Syntax: .go xy #x #y [#mapid]\r\nTeleport player to point with (#x,#y) coordinates at ground(water) level at map #mapid or same map if #mapid not provided.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go xyz',2,'Syntax: .go xyz #x #y #z [#mapid]\r\nTeleport player to point with (#x,#y,#z) coordinates at ground(water) level at map #mapid or same map if #mapid not provided.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('go zonexy',2,'Syntax: .go zonexy #x #y [#zone]\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject activate',2,'Syntax: .gobject activate #guid\r\nActivates an object like a door or a button.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject add',1024,'Syntax: .gobject add #id [#spawntimeSecs]\r\nAdd a game object from game object templates to the world at your current location using the #id. Spawntimesecs sets the spawntime, it is optional.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject addtemp',256,'Syntax: .gobject addtemp #entry\r\nAdds a temporary gameobject that is not saved to DB.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject delete',1024,'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject grid',2,'Syntax: .gobject grid\r\nOutput gameobjects at distance 20yd from player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject move',512,'Syntax: .gobject move #goguid [#x #y #z]\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject near ',2,'Syntax: .gobject near  [#distance]\r\nOutput gameobjects at distance #distance from player. Output gameobject guids and coordinates sorted by distance from character. If #distance not provided use 10 as default value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject target',2,'Syntax: .gobject target [#go_id|#go_name_part]\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gobject turn',256,'Syntax: .gobject turn #goguid\r\nSet for gameobject #goguid orientation same as current character orientation.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('goname',2,'Syntax: .goname $charactername\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait, e.g. when you are in a group.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('gps',2,'Syntax: .gps\r\nDisplay the position information for a selected character or creature. Position information includes X, Y, Z, and orientation, map Id and zone Id');
insert  into `command`(`name`,`permission_mask`,`help`) values ('groupgo',256,'Syntax: .groupgo $charactername\r\nTeleport the given character and his group to you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guid',512,'Syntax: .guid\r\nDisplay the GUID for the selected character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild ann',1,'Syntax: .guild ann $msg\r\nAdds #msg to guild announce queue.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild create',2048,'Syntax: .guild create $GuildLeaderName $GuildName\r\nCreate a guild named $GuildName with the player $GuildLeaderName as leader.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild delete',2048,'Syntax: .guild delete $GuildName\r\nDelete guild $GuildName.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild disable announce',512,'Syntax: .guild disable announce #name\r\nDisables guild announce system for given guild.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild enable announce',512,'Syntax: .guild enable announce #name\r\nEnables guild announce system for given guild.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild invite',2048,'Syntax: .guild invite $CharacterName $GuildName\r\nAdd $CharacterName into a guild $GuildName.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild rank',2048,'Syntax: .guild rank $CharacterName #Rank\r\nSet for $CharacterName rank #Rank in a guild.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('guild uninvite',2048,'Syntax: .guild uninvite $CharacterName\r\nRemove $CharacterName from a guild.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('help',1,'Syntax: .help [$command]\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('hidearea',4096,'Syntax: .hidearea #areaid\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('honor add',4096,'Syntax: .honor add $amount\r\nAdd a certain amount of honor (gained today) to the selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('honor addkill',4096,'Syntax: .honor addkikll\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)');
insert  into `command`(`name`,`permission_mask`,`help`) values ('honor update',4096,'Syntax: .honor update\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('hover',2048,'Syntax: .hover #flag\r\nEnable or disable hover mode for your character.\r\nUse a #flag of value 1 to enable, use a #flag value of 0 to disable hover.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('instance listbinds',256,'Syntax: .instance listbinds\r\nLists the binds of the selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('instance savedata',2048,'Syntax: .instance savedata\r\nSave the InstanceData for the current player\'s map to the DB.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('instance selfunbind',2,'Syntax: .instance selfunbind all/$id\r\nClears all binds or given id bind from self.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('instance stats',256,'Syntax: .instance stats\r\nShows statistics about instances.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('instance unbind',2048,'Syntax: .instance unbind all/$id\r\nAll (or given id) of the selected player\'s binds will be cleared.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('itemmove',8192,'Syntax: .itemmove #sourceslotid #destinationslotid\r\nMove an item from slots #sourceslotid to #destinationslotid in your inventory\r\nNot yet implemented');
insert  into `command`(`name`,`permission_mask`,`help`) values ('kick',512,'Syntax: .kick [$charactername] [$reason]\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is \"No Reason\".');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn',2048,'Syntax: .learn #parameter\r\nSelected character learn a spell of id #parameter.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all',8192,'Syntax: .learn all\r\nLearn all big set different spell maybe useful for Administaror.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_crafts',2048,'Syntax: .learn crafts\r\nLearn all professions and recipes.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_default',2048,'Syntax: .learn all_default [$playername]\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_gm',2048,'Syntax: .learn all_gm\r\nLearn all default spells for Game Masters.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_lang',2048,'Syntax: .learn all_lang\r\nLearn all languages');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_myclass',8192,'Syntax: .learn all_myclass\r\nLearn all spells and talents available for his class.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_myspells',8192,'Syntax: .learn all_myspells\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_mytalents',2048,'Syntax: .learn all_mytalents\r\nLearn all talents (and spells with first rank learned as talent) available for his class.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('learn all_recipes',2048,'Syntax: .learn all_recipes [$profession]\r\nLearns all recipes of specified profession and sets skill level to max.\r\nExample: .learn all_recipes enchanting');
insert  into `command`(`name`,`permission_mask`,`help`) values ('levelup',2048,'Syntax: .levelup [$playername] [#numberoflevels]\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('linkgrave',4096,'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('list auras',2,'Syntax: .list auras\r\nOutput selected unit auras.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('list creature',2,'Syntax: .list creature #creature_id [#max_count]\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('list item',8192,'Syntax: .list item #item_id [#max_count]\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('list object',2,'Syntax: .list object #gameobject_id [#max_count]\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('listfreeze',512,'Syntax: .listfreeze\r\nSearch and output all frozen players.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('loadscripts',4096,'Syntax: .loadscripts $scriptlibraryname\r\nUnload current and load the script library $scriptlibraryname or reload current if $scriptlibraryname omitted, in case you changed it while the server was running.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lockaccount',1,'Syntax: .lockaccount [on|off]\r\nAllow login from account only from current used IP or remove this requirement.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup area',2,'Syntax: .lookup area $namepart\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup creature',2,'Syntax: .lookup creature $namepart\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup event',2,'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup faction',2,'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup item',2,'Syntax: .lookup item $itemname\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup itemset',2,'Syntax: .lookup itemset $itemname\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup object',2,'Syntax: .lookup object $objname\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup player account',512,'Syntax : .lookup player account $account ($limit)\r\nSearchs players, which account username is $account with optional parametr $limit of results.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup player email',2048,'Syntax : .lookup player email $email ($limit)\r\nSearchs players, which account email is $email with optional parametr $limit of results.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup player ip',512,'Syntax : .lookup player ip $ip ($limit)\r\nSearchs players, which account ast_ip is $ip with optional parametr $limit of results.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup quest',2,'Syntax: .lookup quest $namepart\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup skill',2,'Syntax: .lookup skill $$namepart\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup spell',2,'Syntax: .lookup spell $namepart\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('lookup tele',2,'Syntax: .lookup tele $substring\r\nSearch and output all .tele command locations with provide $substring in name.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('maxskill',2048,'Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum values for its current level.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify arena',4096,'Syntax: .modify arena #value\r\nAdd $amount arena points to the selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify aspeed',256,'Syntax: .modify aspeed #rate\r\nModify all speeds -run,swim,run back,swim back- of the selected player to \"normalbase speed for this move type\"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 10.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify bit',2048,'Syntax: .modify bit #field #bit\r\nToggle the #bit bit of the #field field for the selected player. If no player is selected, modify your character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify bwalk',256,'Syntax: .modify bwalk #rate\r\nModify the speed of the selected player while running backwards to \"normal walk back speed\"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 10.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify drunk',2,'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify energy',256,'Syntax: .modify energy #energy\r\nModify the energy of the selected player. If no player is selected, modify your energy.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify faction',2048,'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify fly',256,'Syntax: .modify fly #rate\r\nModify the speed of the selected player while flying to \"normal fly speed\"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 30.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify gender',2048,'Syntax: .modify gender male/female\r\nChange gender of selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify honor',2048,'Syntax: .modify honor $amount\r\nAdd $amount honor points to the selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify hp',256,'Syntax: .modify hp #newhp\r\nModify the hp of the selected player. If no player is selected, modify your hp.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify mana',256,'Syntax: .modify mana #newmana\r\nModify the mana of the selected player. If no player is selected, modify your mana.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify Mod32Value',2048,'Syntax: .Mod32Value #field #value\r\nAdd #value to field #field of your character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify money',2048,'Syntax: .modify money #money\r\nAdd or remove money to the selected player. If no player is selected, modify your money. #gold can be negative to remove money.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify morph',256,'Syntax: .modify morph #displayid\r\nChange your current model id to #displayid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify mount',256,'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify rage',256,'Syntax: .modify rage #newrage\r\nModify the rage of the selected player. If no player is selected, modify your rage.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify rep',2048,'Syntax: .modify rep #repId (#repvalue | $rankname [#delta])\r\nSets the selected players reputation with faction #repId to #repvalue or to $reprank. If the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\r\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify scale',256,'Syntax: .modify scale #rate\r\nModify character scale. Rate may range from 0.01 to 10.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify speed',256,'Syntax: .modify speed #rate\r\nModify the running speed of the selected player to \"normal base run speed\"*rate. If no player is selected, modify your speed.\r\n #rate may range from 0.1 to 10.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify spell',8192,'Syntax: .modify spell $spellflatid $op $val [$mark]\r\nWTF is that ... ? oO');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify standstate',2048,'Syntax: .modify standstate $anim\r\nModifies emote state.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify swim',256,'Syntax: .modify swim #rate\r\nModify the swim speed of the selected player to \"normal swim speed\"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 10.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify titles',2048,'Syntax: .modify titles #mask\r\nAllows user to use all titles from #mask. #mask=0 disables the title-choose-field');
insert  into `command`(`name`,`permission_mask`,`help`) values ('modify tp',2048,'Syntax: .modify tp $count\r\nAdds $count free talent points.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('movegens',2,'Syntax: .movegens\r\nShow movement generators stack for selected creature or player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('mute',512,'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('muteinfo',512,'Syntax: .muteinfo $nick\r\nShows mute history for player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('nameannounce',256,'Syntax: .nameannounce $text\r\nShows server wide message displaying sender name.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('namego',256,'Syntax: .namego $charactername\r\nTeleport the given character to you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('neargrave',256,'Syntax: .neargrave [alliance|horde]\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('notify',2048,'Syntax: .notify $MessageToBroadcast\r\nSend a global message to all players online in screen.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc add',1024,'Syntax: .npc add #creatureid\r\nSpawn a creature by the given template id of #creatureid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc addformation',2048,'Syntax: .npc addformation #guid\r\nAdd formation with creature with #guid as leader to formations.txt.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc additem',2048,'Syntax: .npc additem #itemId <#maxcount><#incrtime><#extendedcost>r\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc addmove',256,'Syntax: .npc addmove #creature_guid [#waittime]\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc addtemp',256,'Adds temporary NPC, not saved to database.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc changeentry',2048,'Syntax: .npc changeentry #entry\r\nChange entry of the selected creature to #entry.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc changelevel',2048,'Syntax: .npc changelevel #level\r\nChange the level of the selected creature to #level. #level may range from 1 to 73.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc delete',1024,'Syntax: .npc delete [#guid]\r\nDelete creature with guid #guid (or the selected if no guid is provided)');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc deleteformation',2048,'Syntax: .npc deleteformation\r\nDelete selected creature formation.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc delitem',2048,'Syntax: .npc delitem #itemId\r\nRemove item #itemid from item list of selected vendor.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc doaction',2048,'Syntax: .npc doaction #action\r\nCalls selected creature AI DoAction method.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc enterevademode',2,'Syntax: .npc enterevademode\r\nForces selected creature to evade.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc factionid',256,'Syntax: .npc factionid #factionid\r\nSet the faction of the selected creature to #factionid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc fieldflags',256,'Syntax: .npc fieldflag #fieldflag\nSet the field flags of creature template of the selected creature and selected creature to #fieldflag. flags will applied to all creatures of selected creature template after server restart or grid unload/load.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc flag',256,'Syntax: .npc flag #npcflag\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc follow',256,'Syntax: .npc follow\r\nSelected creature start follow you until death/fight/etc.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc info',2,'Syntax: .npc info\r\nDisplay a list of details for the selected creature.\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n- Field flags, dynamic flags, faction template,\r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc move',1024,'Syntax: .npc move [#creature_guid]\r\nMove the targeted creature spawn point to your coordinates.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc playemote',2048,'Syntax: .npc playemote #emoteid\r\nMake the selected creature emote with an emote of id #emoteid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc resetai',256,'Syntax: .npc resetai\r\nResets selected creature AI.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc say',1024,'Syntax: .npc say $text\r\nForce selected npc to say $text.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc setlink',256,'Syntax: .npc setlink #linkguid\r\nLinks selected creature to creature with guid #linkguid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc setmodel',1024,'Syntax: .npc setmodel #displayid\r\nChange the model id of the selected creature to #displayid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc setmovetype',256,'Syntax: .npc setmovetype [#creature_guid] stay/random/way [NODEL]\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc spawndist',256,'Syntax: .npc spawndist #dist\r\nAdjust spawndistance of selected creature to dist.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc spawntime',256,'Syntax: .npc spawntime #time\r\nAdjust spawntime of selected creature to time.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc textemote',2048,'Syntax: .npc textemote #emoteid\r\nMake the selected creature to do textemote with an emote of id #emoteid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc unfollow',256,'Syntax: .npc unfollow\r\nSelected creature (non pet) stop follow you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc whisper',1024,'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('npc yell',1,'Syntax: .npc yell $text\r\nForce selected npc to yell $text.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('password',1,'Syntax: .password $old_password $new_password $new_password\r\nChange your account password.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path add',256,'Syntax: .path add [$pathid]\r\nAdds waypoint to path');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path event',256,'Syntax: .path event add/mod/del/listid $id');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path load',256,'Syntax: .path load $id');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path modify',256,'Syntax: .path modify delay/action/action_chance/move_flag/del/move/wpadd');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path reloadpath',256,'Syntax: .path reloadpath $id\r\nReloads path given id.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path show',256,'Syntax: .path show on/off/first/last/info [$guid]');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path tofile',4096,'Syntax: .path tofile\r\nAdds current place as a waypoint for selected creature to waypoints.txt file.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('path unload',256,'Syntax: .path unload');
insert  into `command`(`name`,`permission_mask`,`help`) values ('pet create',2048,'Syntax: .pet create\r\nCreates a pet of the selected creature.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('pet learn',2048,'Syntax: .pet learn\r\nLearn #spellid to pet.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('pet tp',2048,'Syntax: .pet tp #\r\nChange pet\'s amount of training points.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('pet unlearn',2048,'Syntax: .pet unlearn\r\nunLearn #spellid to pet.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('pinfo',512,'Syntax: .pinfo [$player_name] [rep]\r\nOutput account information for selected player or player find by $player_name. If \"rep\" parameter provided show reputation information for player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('playall',4096,'Syntax: .playall #soundid\r\nPlayer a sound to whole server.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('plimit',4096,'Syntax: .plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file');
insert  into `command`(`name`,`permission_mask`,`help`) values ('possess',4096,'Syntax: .possess\r\nPossesses indefinitely the selected creature.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('quest add',512,'Syntax: .quest add #quest_id\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('quest complete',512,'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('quest remove',512,'Syntax: .quest remove #quest_id\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('recall',256,'Syntax: .recall [$playername]\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload',4096,'Syntax: .reload table_name\r\nReload table `table_name` if reload support added for this table and this table can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload access_requirement',4096,'Usage: .reload access_requirement\r\nReloads the access_requirement DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all',4096,'Syntax: .reload all\r\nReload all tables with reload support added and that can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_area',4096,'Syntax: .reload all_area\r\nReload all `areatrigger_*` tables if reload support added for this table and this table can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_item',4096,'Syntax: .reload all_item\r\nReload PageTexts and ItemEnchantments tables.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_locales',4096,'Syntax: .reload all_locales\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_loot',4096,'Syntax: .reload all_loot\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_npc',4096,'Syntax: .reload all_npc\r\nReload all npc_* tables with reload support added and that can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_quest',4096,'Syntax: .reload all_quest\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_scripts',4096,'Syntax: .reload all_scripts\r\nReload all *_scripts tables with reload support added and that can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload all_spell',4096,'Syntax: .reload all\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload areatrigger_involvedrelation',4096,'Usage: .reload areatrigger_involvedrelation\r\nReloads the areatrigger_involvedrelation DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload areatrigger_tavern',4096,'Usage: .reload areatrigger_tavern\r\nReloads the areatrigger_tavern DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload areatrigger_teleport',4096,'Usage: .reload areatrigger_teleport\r\nReloads the areatrigger_teleport DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload auctions',4096,'Usage: .reload auctions\r\nReloads the auctions DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload autobroadcast',4096,'Usage: .reload autobroadcast\r\nReloads the autobroadcast DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload command',4096,'Usage: .reload command\r\nReloads the command DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload config',4096,'Syntax: .reload config\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload creature_ai_scripts',4096,'Usage: .reload creature_ai_scripts\r\nReloads the creature_ai_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload creature_involvedrelation',4096,'Usage: .reload creature_involvedrelation\r\nReloads the creature_involvedrelation DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload creature_linked_respawn',4096,'Usage: .reload creature_linked_respawn\r\nReloads the creature_linked_respawn DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload creature_loot_template',4096,'Usage: .reload creature_loot_template\r\nReloads the creature_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload creature_questrelation',4096,'Usage: .reload creature_questrelation\r\nReloads the creature_questrelation DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload disenchant_loot_template',4096,'Usage: .reload disenchant_loot_template\r\nReloads the disenchant_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload eventai',4096,'Usage: .reload eventai\r\nReloads the eventai DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload event_scripts',4096,'Usage: .reload event_scripts\r\nReloads the event_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload fishing_loot_template',4096,'Usage: .reload fishing_loot_template\r\nReloads the fishing_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload gameobject_involvedrelation',4096,'Usage: .reload gameobject_involvedrelation\r\nReloads the gameobject_involvedrelation DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload gameobject_loot_template',4096,'Usage: .reload gameobject_loot_template\r\nReloads the gameobject_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload gameobject_questrelation',4096,'Usage: .reload gameobject_questrelation\r\nReloads the gameobject_questrelation DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload gameobject_scripts',4096,'Usage: .reload gameobject_scripts\r\nReloads the gameobject_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload game_graveyard_zone',4096,'Usage: .reload game_graveyard_zone\r\nReloads the game_graveyard_zone DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload game_tele',4096,'Usage: .reload game_tele\r\nReloads the game_tele DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload gm_tickets',4096,'Usage: .reload gm_tickets\r\nReloads GM Tickets from the database and re-caches them into memory.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload item_enchantment_template',4096,'Usage: .reload item_enchantment_template\r\nReloads the item_enchantment_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload item_loot_template',4096,'Usage: .reload item_loot_template\r\nReloads the item_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload locales_creature',4096,'Usage: .reload locales_creature\r\nReloads the locales_creature DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload locales_gameobject',4096,'Usage: .reload locales_gameobject\r\nReloads the locales_gameobject DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload locales_item',4096,'Usage: .reload locales_item\r\nReloads the locales_item DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload locales_npc_text',4096,'Usage: .reload locales_npc_text\r\nReloads the locales_npc_text DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload locales_page_text',4096,'Usage: .reload locales_page_text\r\nReloads the locales_page_text DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload locales_quest',4096,'Usage: .reload locales_quest\r\nReloads the locales_quest DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload npc_gossip',4096,'Usage: .reload npc_gossip\r\nReloads the npc_gossip DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload npc_option',4096,'Usage: .reload npc_option\r\nReloads the npc_option DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload npc_trainer',4096,'Usage: .reload npc_trainer\r\nReloads the npc_trainer DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload npc_vendor',4096,'Usage: .reload npc_vendor\r\nReloads the npc_vendor DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload page_text',4096,'Usage: .reload page_text\r\nReloads the page_text DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload pickpocketing_loot_template',4096,'Usage: .reload pickpocketing_loot_template\r\nReloads the pickpocketing_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload prospecting_loot_template',4096,'Usage: .reload prospecting_loot_template\r\nReloads the prospecting_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload quest_end_scripts',4096,'Usage: .reload quest_end_scripts\r\nReloads the quest_end_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload quest_mail_loot_template',4096,'Usage: .reload quest_mail_loot_template\r\nReloads the quest_mail_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload quest_start_scripts',4096,'Usage: .reload quest_start_scripts\r\nReloads the quest_start_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload quest_template',4096,'Usage: .reload quest_template\r\nReloads the quest_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload reference_loot_template',4096,'Usage: .reload reference_loot_template\r\nReloads the reference_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload reputation_reward_rate',4096,'Usage: .reload reputation_reward_rate\r\nReloads the reputation_reward_rate DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload reputation_spillover_template',4096,'Usage: .reload reputation_spillover_template\r\nReloads the reputation_spillover_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload reserved_name',4096,'Usage: .reload reserved_name\r\nReloads the reserved_name DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload skill_discovery_template',4096,'Usage: .reload skill_discovery_template\r\nReloads the skill_discovery_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload skill_extra_item_template',4096,'Usage: .reload skill_extra_item_template\r\nReloads the skill_extra_item_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload skill_fishing_base_level',4096,'Usage: .reload skill_fishing_base_level\r\nReloads the skill_fishing_base_level DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload skinning_loot_template',4096,'Usage: .reload skinning_loot_template\r\nReloads the skinning_loot_template DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_affect',4096,'Usage: .reload spell_affect\r\nReloads the spell_affect DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_disabled',4096,'Usage: .reload spell_disabled\r\nReloads the spell_disabled DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_elixir',4096,'Usage: .reload spell_elixir\r\nReloads the spell_elixir DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_enchant_proc_data',4096,'Usage: .reload spell_enchant_proc_data\r\nReloads the spell_enchant_proc_data DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_pet_auras',4096,'Usage: .reload spell_pet_auras\r\nReloads the spell_pet_auras DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_proc_event',4096,'Usage: .reload spell_proc_event\r\nReloads the spell_proc_event DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_required',4096,'Usage: .reload spell_required\r\nReloads the spell_required DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_scripts',4096,'Usage: .reload spell_scripts\r\nReloads the spell_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_script_target',4096,'Usage: .reload spell_script_target\r\nReloads the spell_script_target DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_target_position',4096,'Usage: .reload spell_target_position\r\nReloads the spell_target_position DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload spell_threats',4096,'Usage: .reload spell_threats\r\nReloads the spell_threats DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload trinity_string',4096,'Usage: .reload trinity_string\r\nReloads the trinity_string DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload unqueue_account',4096,'Usage: .reload unqueue_account\r\nReloads the unqueue_account DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reload waypoint_scripts',4096,'Usage: .reload waypoint_scripts.\r\nReloads the waypoint_scripts DB table.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('rename',2048,NULL);
insert  into `command`(`name`,`permission_mask`,`help`) values ('repairitems',256,'Syntax: .repairitems\r\nRepair all selected player\'s items.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reset all',4096,'Syntax: .reset all spells\r\nSyntax: .reset all talents\r\nRequest reset spells or talents at next login each existed character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reset honor',4096,'Syntax: .reset honor [Playername]\r\nReset all honor data for targeted character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reset level',4096,'Syntax: .reset level [Playername]\r\nReset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reset spells',4096,'Syntax: .reset spells [Playername]\r\nRemoves all non-original spells from spellbook. Playername can be name of offline character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reset stats',4096,'Syntax: .reset stats [Playername]\r\nResets(recalculate) all stats of the targeted player to their original values at current level.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('reset talents',4096,'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player. Playername can be name of offline character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('respawn',256,'Syntax: .respawn\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('revive',256,'Syntax: .revive\r\nRevive the selected player. If no player is selected, it will revive you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('revivegroup',2048,'Syntax: .revivegroup\r\nRevives all players in group and teleports them to command user.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('save',4096,'Syntax: .save\r\nSaves your character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('send items',2048,'Syntax: .send items #playername \"#subject\" \"#text\" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\nSend a mail to a player. Subject and mail text must be in \"\". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('send mail',512,'Syntax: .send mail #playername \"#subject\" \"#text\"\r\nSend a mail to a player. Subject and mail text must be in \"\".');
insert  into `command`(`name`,`permission_mask`,`help`) values ('send message',2048,'Syntax: .send message $playername $message\r\nSend screen message to player from ADMINISTRATOR.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('send money',2048,'Syntax: .send money #playername \"#subject\" \"#text\" #money\r\nSend mail with money to a player. Subject and mail text must be in \"\".');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server corpses',4096,'Syntax: .server corpses\r\nTriggering corpses expire check in world.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server exit',4096,'Syntax: .server exit\r\nTerminate trinity-core NOW. Exit code 0.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server idlerestart',4096,'Syntax: .server idlerestart #delay\r\nRestart the server after #delay seconds if no active connections are present (no players). Use #exist_code or 2 as program exist code.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server idlerestart cancel',4096,'Syntax: .server idlerestart cancel\r\nCancel the restart/shutdown timer if any.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server idleshutdown',2048,'Syntax: .server idleshutdown #delay [#exist_code]\r\nShut the server down after #delay seconds if no active connections are present (no players). Use #exist_code or 0 as program exist code.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server idleshutdown cancel',4096,'Syntax: .server idleshutdown cancel\r\nCancel the restart/shutdown timer if any.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server info',1,'Syntax: .server info\r\nDisplay server version and the number of connected players.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server motd',4096,'Syntax: .server motd\r\nShow server Message of the day.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server restart',4096,'Syntax: .server restart #delay\r\nRestart the server after #delay seconds. Use #exist_code or 2 as program exist code.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server restart cancel',4096,'Syntax: .server restart cancel\r\nCancel the restart/shutdown timer if any.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server rollshutdown',4096,'Syntax: .server rollshutdown #delay #msg\r\nShut the server down after #delay seconds and sends announce with #msg as text.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server set difftime',4096,'Syntax: .server set difftime #interval\r\nSet server diff time.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server set loglevel',4096,'Syntax: .server set loglevel #level\r\nSet server log level (0 - errors only, 1 - basic, 2 - detail, 3 - debug).');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server set motd',4096,'Syntax: .server set motd $MOTD\r\nSet server Message of the day.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server shutdown',4096,'Syntax: .server shutdown #delay [#exist_code]\r\nShut the server down after #delay seconds. Use #exist_code or 0 as program exist code.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('server shutdown cancel',4096,'Syntax: .server shutdown cancel\r\nCancel the restart/shutdown timer if any.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('setskill',2048,'Syntax: .setskill #skill #level [#max]\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('showarea',2048,'Syntax: .showarea #areaid\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('showhonor',1,'Syntax: .showhonor\r\nDisplay your honor ranking.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('start',512,'Syntax: .start\r\nTeleport you to the starting area of your character.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('taxicheat',2048,'Syntax: .taxicheat on/off\r\nTemporary grant access or remove to all taxi routes for the selected character. If no character is selected, hide or reveal all routes to you. Visited taxi nodes sill accessible after removing access.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('tele',2,'Syntax: .tele #location\r\nTeleport player to a given location.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('tele add',256,'Syntax: .tele add $name\r\nAdd current your position to .tele command target locations list with name $name.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('tele del',512,'Syntax: .tele del $name\r\nRemove location with name $name for .tele command locations list.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('tele group',2048,'Syntax: .tele group#location\r\nTeleport a selected player and his group members to a given location.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('tele name',512,'Syntax: .tele name #playername #location\r\nTeleport a player to a given location.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket assign',512,'Syntax: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket close',512,'Syntax: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket closedlist',512,'Syntax: .ticket closedlist\r\nDisplays a list of closed GM tickets.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket comment',512,'Syntax: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket delete',2048,'Syntax: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket list',512,'Syntax: .ticket list\r\nDisplays a list of open GM tickets.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket onlinelist',512,'Syntax: .ticket onlinelist\r\nDisplays a list of open GM tickets whose owner is online.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket response',512,'Syntax: .ticket response #id #msg\r\nSends mail to player who opens ticket with id #id and closes this ticket.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket unassign',512,'Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket viewid',512,'Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('ticket viewname',512,'Usage: .ticket viewname $creatorname.\r\nReturns details about specified ticket. Ticket must be open and not deleted.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unaura',256,'Syntax: .unaura #spellid\r\nRemove aura due to spell #spellid from the selected Unit.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unban account',512,'Syntax is: unban account $Name\r\nUnban accounts for account name pattern.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unban character',512,'Syntax is: unban character $Name\r\nUnban accounts for character name pattern.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unban email',2048,'Syntax: .unban email $email\r\nUnbans email address for $email pattern');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unban ip',512,'Syntax is: unban ip $Ip\r\nUnban accounts for IP pattern.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unbindfollow',256,'Syntax: .unbindfollow\r\nRemoves follow binding.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unbindsight',256,'Syntax: .unbindsight\r\nRemoves bound vision. Cannot be used while currently possessing a target.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unfreeze',512,'Syntax: .unfreeze (#player)\r\n\"Unfreezes\" #player and enables his chat again. When using this without #name it will unfreeze your target.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unlearn',512,'Syntax: .unlearn #startspell #endspell\r\nUnlearn for selected player the range of spells between id #startspell and #endspell. If no #endspell is provided, just unlearn spell of id #startspell.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unmute',512,'Syntax: .unmute $playerName\r\nRestore chat messaging for any character from account of character $playerName.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('unpossess',2048,'Syntax: .unpossess\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('waterwalk',512,'Syntax: .waterwalk on/off\r\nSet on/off waterwalk state for selected player or self if no player selected.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wchange',2048,'Syntax: .wchange #weathertype #status\r\nSet current weather to #weathertype with an intensity of #status. #weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('weather',1,'Syntax: .weather on/off\r\nEnable/Disable weather changing for account.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('whispers',512,'Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use trinityd.conf setting.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp add',256,'Syntax: .wp add [$pathid]\r\nAdds waypoint to path');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp event',256,'Syntax: .wp event add/mod/del/listid $id');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp load',256,'Syntax: .wp load $id');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp modify',256,'Syntax: .wp modify delay/action/action_chance/move_flag/del/move/wpadd');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp reloadpath',256,'Syntax: .wp reloadpath $id\r\nReloads path given id.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp show',256,'Syntax: .wp show on/off/first/last/info [$guid]');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp tofile',4096,'Syntax: .wp tofile\r\nAdds current place as a waypoint for selected creature to waypoints.txt file.');
insert  into `command`(`name`,`permission_mask`,`help`) values ('wp unload',256,'Syntax: .wp unload');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
